-- CreateTable
CREATE TABLE "Submission" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "requestDate" DATETIME NOT NULL,
    "requestorName" TEXT NOT NULL,
    "requestorRoleTeam" TEXT NOT NULL,
    "sponsorApprover" TEXT NOT NULL,
    "projectName" TEXT NOT NULL,
    "priority" TEXT NOT NULL,
    "systemWhatDoesItDo" TEXT NOT NULL,
    "aiAutomationType" JSONB NOT NULL,
    "aiAutomationTypeOther" TEXT,
    "vendorModelPlatform" TEXT,
    "deploymentModel" TEXT NOT NULL,
    "endUsers" TEXT NOT NULL,
    "dataIngested" TEXT,
    "outputsProduced" TEXT,
    "dataSensitivity" TEXT NOT NULL,
    "impactIfFails" TEXT NOT NULL,
    "humanOversight" TEXT,
    "biasFairnessRisks" TEXT NOT NULL,
    "thirdPartyVendorRisk" TEXT NOT NULL,
    "accessControls" TEXT NOT NULL,
    "loggingMonitoring" TEXT,
    "incidentResponsePlan" TEXT NOT NULL,
    "rollbackPlan" TEXT,
    "dataRetentionDisposal" TEXT NOT NULL,
    "testingValidationDone" TEXT NOT NULL,
    "legalComplianceReviewRequired" TEXT NOT NULL,
    "isAIConfirmed" BOOLEAN NOT NULL,
    "riskScore" INTEGER NOT NULL,
    "riskLevel" TEXT NOT NULL,
    "triageOutcome" TEXT NOT NULL,
    "routingRecommendation" JSONB NOT NULL,
    "conditionsInfoNeeded" JSONB NOT NULL,
    "requiredControlsChecklist" JSONB NOT NULL
);
